apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produto
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-produto
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
      labels:
        app: api-produto
    spec:
      containers:
        - name: api-produto
          image: davarski/api-produto:v1.0.0
          ports:
          - containerPort: 80
          env: 
          - name: MONGODB_URI
            value: mongodb://mongouser:apiproduto@mongodb-service:27017/admin
---

apiVersion: v1
kind: Service
metadata:
  name: api-produto-service
spec:
  selector:
    app: api-produto
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort
